openapi: 3.0.0
info:
  title: Travel API
  version: 1.0.0

paths:
  /api/request:
    post:
      summary: Process user request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: UUID of the user
                text:
                  type: string
                  description: Request text from the user
              required:
                - id
                - text
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      type:
                        type: string
                        enum: [message]
                      text:
                        type: string
                        description: Markdown formatted message
                  - type: object
                    properties:
                      type:
                        type: string
                        enum: [schedule]
                      objects:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              enum: [bus, train, plane, ship, walk]
                            time_start_utc:
                              type: integer
                              description: Start time in UTC
                            time_end_utc:
                              type: integer
                              description: End time in UTC
                            place_start:
                              type: string
                              description: Start location
                            place_finish:
                              type: string
                              description: End location
                            ticket_url:
                              type: string
                              description: URL for the ticket
        '500':
          description: Internal Server Error
